name: Build and test
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        py:
          - "3.7"
          - "3.8"
          - "3.9"
        os:
          - "ubuntu-latest"
    name: "Python: ${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
          architecture: x64
      - run: pip install tox
      - name: Run tox
        run: tox -e py
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64
      - run: pip install tox
      - run: tox -e lint